# Generated by Django 5.0.6 on 2024-07-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_initial'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='exercise',
        ),
        migrations.AddField(
            model_name='log',
            name='exercises',
            field=models.ManyToManyField(related_name='logs', to='exercise.exercise'),
        ),
    ]
