# Generated by Django 5.0.6 on 2024-07-10 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('exercise', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='owner',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='category.category'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
